#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export APPDIR="$HERE"
export LD_LIBRARY_PATH="${HERE}/lib-local:${LD_LIBRARY_PATH}"
export PATH="${HERE}/bin-local:${PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share:${XDG_DATA_DIRS}"
exec "${HERE}/bin-local/windusb-gui" "$@"